language: java
install: "chmod +x gradlew"
script: ./gradlew setupCIWorkspace build
before_deploy: "echo 'before deploy'"
deploy:
    provider: releases
    api-key: "a03e859e331fb219a570bbe0bd4eff4917852562"
    file: "build/libs/*"
    skip_cleanup: true
    on:
        all_branches: true
after_deploy: "echo 'after deploy'"